### ISSUE TITLE
Lab 10 -Review by Caretto Michelangelo s310178 

### ISSUE THREAD

**Issue by rasenqt** [SilvioChito/computational_intelligence#3]
Hi Silvio,
I really liked the way you implemented Reinforcment Learning.
You played on the "Reward" by using your knowledge about this game, and I think that using winning heuristic sometimes lead to big improvements or just to an early convergence  in order to skip some steps.
Next time i would to see more about test like the draw or lost percentage or the percentage if opponents have the first move.
Anyway Good Job and HAVE FUN in your VACATION!

**Comment by SilvioChito** [comment]
Thank you so much, I really appreciate that ! I'll defenitely  work on more explanatory results
